name: Build Extension

on:
  push:
    branches:
      - main
    paths:
      - 'packages/extension/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 9.x

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Get package info
        id: package
        run: |
          echo "name=$(node -p "require('./packages/extension/package.json').name")" >> $GITHUB_OUTPUT
          echo "version=$(node -p "require('./packages/extension/package.json').version")" >> $GITHUB_OUTPUT

      - name: Build extensions
        run: |
          cd packages/extension
          pnpm pack:all

      - name: Commit changes
        if: github.ref == 'refs/heads/main'
        run: |
          git checkout main
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -f packages/extension/build/*.zip
          git diff --staged --quiet || (git commit -m "chore: update extension builds [skip ci]" && git push)

      - name: Validate lock file
        run: |
          pnpm install --frozen-lockfile

      - name: Check duplicates
        run: pnpm dedupe --check
